[book]
authors = ["iodapson"]
language = "en"
multilingual = false
src = "src"
title = "Tour of Rust's Standard Library Traits (in mdbook!)"

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = false          # displays a run button for rust code

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
